server:
  port: 9081
  servlet:
    context-path: /travelagency

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 11MB
#  datasource:
#    url: jdbc:mysql://localhost:3306/bumerang
#    username: travelagency
#    password: Bum3r4n6*
#    driverClassName: com.mysql.cj.jdbc.Driver


#QA DB
  datasource:
#    url: jdbc:mysql://containers-us-west-190.railway.app:6121/railway
    url: ${datasource_url}
#    username: root
    username: ${user_name}
    password: ${db_password}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  sendgrid:
    api-key: ${sendgrid_apikey}

#travelagency jwtsecret
bumeran:
  jwtSecret: ======================Bum3r4n6*===========================
  jwtExpirationMs: 86400000


#  mysql://root:9Ik8IFqnVDmPcFuaFtne@containers-us-west-190:
#    railway:
#      app:6121/railway:

#  containers-us-west-190.railway.app

#  6121

#  9Ik8IFqnVDmPcFuaFtne

  mail:
    sender: 'bumeran.travels@gmail.com'
    from-name: 'Viajes Bumeran'
    send-grid-templates:
      reset-password-id: 'd-7d80d0c386ca45088bd6fbb7946bc8d8'