server:
  port: 9081
  servlet:
    context-path: /travelagency

spring:
  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 11MB
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/bumerang
  #    username: travelagency
  #    password: Bum3r4n6*
  #    driverClassName: com.mysql.cj.jdbc.Driver


  #QA DB
  datasource:
    #    url: jdbc:mysql://containers-us-west-190.railway.app:6121/railway
    url: jdbc:mysql://database-bumeran.c6omhk7yegm2.us-east-2.rds.amazonaws.com:3306/bumeran
    #    username: root
    username: bumeran
    password: 9Ik8IFqnVDmPcFuaFtne
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifeTime: 600000
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none

  sendgrid:
    api-key: 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

#travelagency jwtsecret
bumeran:
  jwtSecret: ======================Bum3r4n6*===========================
  jwtExpirationMs: 86400000


  #  mysql://root:9Ik8IFqnVDmPcFuaFtne@containers-us-west-190:
  #    railway:
  #      app:6121/railway:

  #  containers-us-west-190.railway.app

  #  6121

  #  9Ik8IFqnVDmPcFuaFtne

  mail:
    sender: 'bumeran.travels@gmail.com'
    from-name: 'Viajes Bumeran'
    send-grid-templates:
      reset-password-id: 'd-7d80d0c386ca45088bd6fbb7946bc8d8'

aws:
  s3:
    bucket:
      name: mybumeranbucket-qa